FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    ca-certificates \
    libstdc++6 \
    libopenblas-dev \
    libgomp1 \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements_embeddings.txt

# Comando final: ejecutar handler serverless
CMD ["python", "serverless_embeddings.py"]
